name: Deploy Fullstack App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      # BACKEND 
      - name: Install backend dependencies
        working-directory: server
        run: npm ci

      - name: Create backend .env file
        working-directory: server
        run: |
          echo "${{ secrets.PROD_BACKEND_ENV }}" > .env

      - name: Run Sequelize migrations
        working-directory: server
        run: |
          npx sequelize-cli db:migrate || echo "No migrations to run"


      - name: Start or Restart backend with PM2
        working-directory: server
        run: |
          pm2 start index.js --name app || pm2 restart app

      # FRONTEND
      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Create frontend .env file
        working-directory: client
        run: |
          echo "${{ secrets.PROD_FRONTEND_ENV }}" > .env

      - name: Build frontend
        working-directory: client
        run: npm run build

      - name: Deploy frontend to Nginx
        run: |
          sudo rm -rf /var/www/html/*
          sudo cp -r client/dist/* /var/www/html/
